apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverse-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reverse-proxy
  template:
    metadata:
      labels:
        app: reverse-proxy
    spec:
      containers:
        - name: reverse-proxy
          image: ghcr.io/r3m1n0x/cert-manager-proxy:main # Replace with your reverse proxy image details
          args:
            - "--backend=http://ingress-nginx-controller:80" # Replace with your backend service details
            - "--frontend=:8080"
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 200m
              memory: 128Mi


